shell.run("copy","disk/os","/os")
shell.run("copy","disk/startup","/startup")
shell.run("copy","disk/users","/users")
shell.run("copy","disk/back.lua","/back.lua")
peripheral.find("drive")
os.pullEvent("disk_eject")
os.reboot()
